sudo: false

language: rust
rust:
    - stable
    - beta
    - nightly

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
    - aptitude

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install zmq ; fi
# So that "libsodium-dev" can be found
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:anton+/dnscrypt ; fi
# So a more recent version of libzmq3-dev can be found
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/ ./" | sudo tee --append /etc/apt/sources.list ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo wget https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/Release.key -O- | sudo apt-key add ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo aptitude install -y libasound2-dev libzmq3-dev libsodium-dev ; fi


# If I get to the point where I want to auto-publish versions...

#after_success:
#    - |
#        [ $TRAVIS_BRANCH = master ] &&
#        [ $TRAVIS_PULL_REQUEST = false ] &&
#        cargo publish --no-verify --token ${CRATESIO_TOKEN}