sudo: false

language: rust
rust:
    - stable
    - beta
    - nightly

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install zmq ; fi
# The next two lines are so that "libsodium-dev" can be found in the third line
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:anton+/dnscrypt ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y -qq libasound2-dev libzmq3-dev libsodium-dev ; fi


# If I get to the point where I want to auto-publish versions...

#after_success:
#    - |
#        [ $TRAVIS_BRANCH = master ] &&
#        [ $TRAVIS_PULL_REQUEST = false ] &&
#        cargo publish --no-verify --token ${CRATESIO_TOKEN}