sudo: false

language: rust
rust:
    - stable

dist: xenial

os:
  - linux
  - osx


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install zmq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libasound2-dev libzmq3-dev libsodium-dev ; fi


# If I get to the point where I want to auto-publish versions...

#after_success:
#    - |
#        [ $TRAVIS_BRANCH = master ] &&
#        [ $TRAVIS_PULL_REQUEST = false ] &&
#        cargo publish --no-verify --token ${CRATESIO_TOKEN}